/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedSadminRouteImport } from './routes/_authenticated/sadmin'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAffiliatesRouteImport } from './routes/_authenticated/admin.affiliates'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin.audit-logs'
import { Route as AuthenticatedAdminControlRouteImport } from './routes/_authenticated/admin.control'
import { Route as AuthenticatedAdminMonitoringRouteImport } from './routes/_authenticated/admin.monitoring'
import { Route as AuthenticatedAdminParsedSignalsRouteImport } from './routes/_authenticated/admin.parsed-signals'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin.payouts'
import { Route as AuthenticatedAdminPromosRouteImport } from './routes/_authenticated/admin.promos'
import { Route as AuthenticatedAdminRiskTemplatesRouteImport } from './routes/_authenticated/admin.risk-templates'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSourcesRouteImport } from './routes/_authenticated/admin.sources'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminTradesRouteImport } from './routes/_authenticated/admin.trades'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppActiveTradesRouteImport } from './routes/_authenticated/app.active-trades'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/app.analytics'
import { Route as AuthenticatedAppBacktestRouteImport } from './routes/_authenticated/app.backtest'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppExchangesRouteImport } from './routes/_authenticated/app.exchanges'
import { Route as AuthenticatedAppHeatmapRouteImport } from './routes/_authenticated/app.heatmap'
import { Route as AuthenticatedAppLeaderboardRouteImport } from './routes/_authenticated/app.leaderboard'
import { Route as AuthenticatedAppMarketplaceRouteImport } from './routes/_authenticated/app.marketplace'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppPreferencesRouteImport } from './routes/_authenticated/app.preferences'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppReferralsRouteImport } from './routes/_authenticated/app.referrals'
import { Route as AuthenticatedAppRiskRouteImport } from './routes/_authenticated/app.risk'
import { Route as AuthenticatedAppRiskOptimizerRouteImport } from './routes/_authenticated/app.risk-optimizer'
import { Route as AuthenticatedAppSourcesRouteImport } from './routes/_authenticated/app.sources'
import { Route as AuthenticatedAppSupportRouteImport } from './routes/_authenticated/app.support'
import { Route as AuthenticatedAppTradeHistoryRouteImport } from './routes/_authenticated/app.trade-history'
import { Route as AuthenticatedSadminIndexRouteImport } from './routes/_authenticated/sadmin.index'
import { Route as AuthenticatedSadminAffiliatesRouteImport } from './routes/_authenticated/sadmin.affiliates'
import { Route as AuthenticatedSadminAuditLogsRouteImport } from './routes/_authenticated/sadmin.audit-logs'
import { Route as AuthenticatedSadminControlRouteImport } from './routes/_authenticated/sadmin.control'
import { Route as AuthenticatedSadminExportRouteImport } from './routes/_authenticated/sadmin.export'
import { Route as AuthenticatedSadminMonitoringRouteImport } from './routes/_authenticated/sadmin.monitoring'
import { Route as AuthenticatedSadminParsedSignalsRouteImport } from './routes/_authenticated/sadmin.parsed-signals'
import { Route as AuthenticatedSadminPaymentsRouteImport } from './routes/_authenticated/sadmin.payments'
import { Route as AuthenticatedSadminPayoutsRouteImport } from './routes/_authenticated/sadmin.payouts'
import { Route as AuthenticatedSadminPromosRouteImport } from './routes/_authenticated/sadmin.promos'
import { Route as AuthenticatedSadminRankBonusesRouteImport } from './routes/_authenticated/sadmin.rank-bonuses'
import { Route as AuthenticatedSadminRiskTemplatesRouteImport } from './routes/_authenticated/sadmin.risk-templates'
import { Route as AuthenticatedSadminSettingsRouteImport } from './routes/_authenticated/sadmin.settings'
import { Route as AuthenticatedSadminSourcesRouteImport } from './routes/_authenticated/sadmin.sources'
import { Route as AuthenticatedSadminSubscriptionsRouteImport } from './routes/_authenticated/sadmin.subscriptions'
import { Route as AuthenticatedSadminSupportRouteImport } from './routes/_authenticated/sadmin.support'
import { Route as AuthenticatedSadminTradesRouteImport } from './routes/_authenticated/sadmin.trades'
import { Route as AuthenticatedSadminUsersRouteImport } from './routes/_authenticated/sadmin.users'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicPaymentWebhookRouteImport } from './routes/api/public/payment-webhook'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram-webhook'
import { Route as ApiPublicHooksDispatchNotificationsRouteImport } from './routes/api/public/hooks/dispatch-notifications'
import { Route as ApiPublicHooksMonitorAnomaliesRouteImport } from './routes/api/public/hooks/monitor-anomalies'
import { Route as ApiPublicHooksMonitorPositionsRouteImport } from './routes/api/public/hooks/monitor-positions'
import { Route as ApiPublicHooksPriceTickRouteImport } from './routes/api/public/hooks/price-tick'
import { Route as ApiPublicHooksProcessOrdersRouteImport } from './routes/api/public/hooks/process-orders'
import { Route as ApiPublicHooksReconcileOrdersRouteImport } from './routes/api/public/hooks/reconcile-orders'
import { Route as ApiPublicHooksRunBacktestsRouteImport } from './routes/api/public/hooks/run-backtests'
import { Route as ApiPublicHooksSyncBalancesRouteImport } from './routes/api/public/hooks/sync-balances'
import { Route as ApiPublicHooksSyncPositionsRouteImport } from './routes/api/public/hooks/sync-positions'
import { Route as ApiPublicHooksWebhookSignalTokenRouteImport } from './routes/api/public/hooks/webhook-signal.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSadminRoute = AuthenticatedSadminRouteImport.update({
  id: '/sadmin',
  path: '/sadmin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAffiliatesRoute =
  AuthenticatedAdminAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminControlRoute =
  AuthenticatedAdminControlRouteImport.update({
    id: '/control',
    path: '/control',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMonitoringRoute =
  AuthenticatedAdminMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParsedSignalsRoute =
  AuthenticatedAdminParsedSignalsRouteImport.update({
    id: '/parsed-signals',
    path: '/parsed-signals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromosRoute =
  AuthenticatedAdminPromosRouteImport.update({
    id: '/promos',
    path: '/promos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRiskTemplatesRoute =
  AuthenticatedAdminRiskTemplatesRouteImport.update({
    id: '/risk-templates',
    path: '/risk-templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSourcesRoute =
  AuthenticatedAdminSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTradesRoute =
  AuthenticatedAdminTradesRouteImport.update({
    id: '/trades',
    path: '/trades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppActiveTradesRoute =
  AuthenticatedAppActiveTradesRouteImport.update({
    id: '/active-trades',
    path: '/active-trades',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBacktestRoute =
  AuthenticatedAppBacktestRouteImport.update({
    id: '/backtest',
    path: '/backtest',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppExchangesRoute =
  AuthenticatedAppExchangesRouteImport.update({
    id: '/exchanges',
    path: '/exchanges',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHeatmapRoute = AuthenticatedAppHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLeaderboardRoute =
  AuthenticatedAppLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMarketplaceRoute =
  AuthenticatedAppMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPreferencesRoute =
  AuthenticatedAppPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReferralsRoute =
  AuthenticatedAppReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRiskRoute = AuthenticatedAppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRiskOptimizerRoute =
  AuthenticatedAppRiskOptimizerRouteImport.update({
    id: '/risk-optimizer',
    path: '/risk-optimizer',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSourcesRoute = AuthenticatedAppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSupportRoute = AuthenticatedAppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTradeHistoryRoute =
  AuthenticatedAppTradeHistoryRouteImport.update({
    id: '/trade-history',
    path: '/trade-history',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedSadminIndexRoute =
  AuthenticatedSadminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminAffiliatesRoute =
  AuthenticatedSadminAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminAuditLogsRoute =
  AuthenticatedSadminAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminControlRoute =
  AuthenticatedSadminControlRouteImport.update({
    id: '/control',
    path: '/control',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminExportRoute =
  AuthenticatedSadminExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminMonitoringRoute =
  AuthenticatedSadminMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminParsedSignalsRoute =
  AuthenticatedSadminParsedSignalsRouteImport.update({
    id: '/parsed-signals',
    path: '/parsed-signals',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminPaymentsRoute =
  AuthenticatedSadminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminPayoutsRoute =
  AuthenticatedSadminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminPromosRoute =
  AuthenticatedSadminPromosRouteImport.update({
    id: '/promos',
    path: '/promos',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminRankBonusesRoute =
  AuthenticatedSadminRankBonusesRouteImport.update({
    id: '/rank-bonuses',
    path: '/rank-bonuses',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminRiskTemplatesRoute =
  AuthenticatedSadminRiskTemplatesRouteImport.update({
    id: '/risk-templates',
    path: '/risk-templates',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminSettingsRoute =
  AuthenticatedSadminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminSourcesRoute =
  AuthenticatedSadminSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminSubscriptionsRoute =
  AuthenticatedSadminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminSupportRoute =
  AuthenticatedSadminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminTradesRoute =
  AuthenticatedSadminTradesRouteImport.update({
    id: '/trades',
    path: '/trades',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const AuthenticatedSadminUsersRoute =
  AuthenticatedSadminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSadminRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentWebhookRoute = ApiPublicPaymentWebhookRouteImport.update({
  id: '/api/public/payment-webhook',
  path: '/api/public/payment-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram-webhook',
    path: '/api/public/telegram-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchNotificationsRoute =
  ApiPublicHooksDispatchNotificationsRouteImport.update({
    id: '/api/public/hooks/dispatch-notifications',
    path: '/api/public/hooks/dispatch-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonitorAnomaliesRoute =
  ApiPublicHooksMonitorAnomaliesRouteImport.update({
    id: '/api/public/hooks/monitor-anomalies',
    path: '/api/public/hooks/monitor-anomalies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonitorPositionsRoute =
  ApiPublicHooksMonitorPositionsRouteImport.update({
    id: '/api/public/hooks/monitor-positions',
    path: '/api/public/hooks/monitor-positions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPriceTickRoute = ApiPublicHooksPriceTickRouteImport.update({
  id: '/api/public/hooks/price-tick',
  path: '/api/public/hooks/price-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessOrdersRoute =
  ApiPublicHooksProcessOrdersRouteImport.update({
    id: '/api/public/hooks/process-orders',
    path: '/api/public/hooks/process-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReconcileOrdersRoute =
  ApiPublicHooksReconcileOrdersRouteImport.update({
    id: '/api/public/hooks/reconcile-orders',
    path: '/api/public/hooks/reconcile-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunBacktestsRoute =
  ApiPublicHooksRunBacktestsRouteImport.update({
    id: '/api/public/hooks/run-backtests',
    path: '/api/public/hooks/run-backtests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncBalancesRoute =
  ApiPublicHooksSyncBalancesRouteImport.update({
    id: '/api/public/hooks/sync-balances',
    path: '/api/public/hooks/sync-balances',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncPositionsRoute =
  ApiPublicHooksSyncPositionsRouteImport.update({
    id: '/api/public/hooks/sync-positions',
    path: '/api/public/hooks/sync-positions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWebhookSignalTokenRoute =
  ApiPublicHooksWebhookSignalTokenRouteImport.update({
    id: '/api/public/hooks/webhook-signal/$token',
    path: '/api/public/hooks/webhook-signal/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/sadmin': typeof AuthenticatedSadminRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/control': typeof AuthenticatedAdminControlRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/parsed-signals': typeof AuthenticatedAdminParsedSignalsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/admin/risk-templates': typeof AuthenticatedAdminRiskTemplatesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/active-trades': typeof AuthenticatedAppActiveTradesRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/backtest': typeof AuthenticatedAppBacktestRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/exchanges': typeof AuthenticatedAppExchangesRoute
  '/app/heatmap': typeof AuthenticatedAppHeatmapRoute
  '/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/risk': typeof AuthenticatedAppRiskRoute
  '/app/risk-optimizer': typeof AuthenticatedAppRiskOptimizerRoute
  '/app/sources': typeof AuthenticatedAppSourcesRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/trade-history': typeof AuthenticatedAppTradeHistoryRoute
  '/sadmin/affiliates': typeof AuthenticatedSadminAffiliatesRoute
  '/sadmin/audit-logs': typeof AuthenticatedSadminAuditLogsRoute
  '/sadmin/control': typeof AuthenticatedSadminControlRoute
  '/sadmin/export': typeof AuthenticatedSadminExportRoute
  '/sadmin/monitoring': typeof AuthenticatedSadminMonitoringRoute
  '/sadmin/parsed-signals': typeof AuthenticatedSadminParsedSignalsRoute
  '/sadmin/payments': typeof AuthenticatedSadminPaymentsRoute
  '/sadmin/payouts': typeof AuthenticatedSadminPayoutsRoute
  '/sadmin/promos': typeof AuthenticatedSadminPromosRoute
  '/sadmin/rank-bonuses': typeof AuthenticatedSadminRankBonusesRoute
  '/sadmin/risk-templates': typeof AuthenticatedSadminRiskTemplatesRoute
  '/sadmin/settings': typeof AuthenticatedSadminSettingsRoute
  '/sadmin/sources': typeof AuthenticatedSadminSourcesRoute
  '/sadmin/subscriptions': typeof AuthenticatedSadminSubscriptionsRoute
  '/sadmin/support': typeof AuthenticatedSadminSupportRoute
  '/sadmin/trades': typeof AuthenticatedSadminTradesRoute
  '/sadmin/users': typeof AuthenticatedSadminUsersRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/telegram-webhook': typeof ApiPublicTelegramWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/sadmin/': typeof AuthenticatedSadminIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/monitor-anomalies': typeof ApiPublicHooksMonitorAnomaliesRoute
  '/api/public/hooks/monitor-positions': typeof ApiPublicHooksMonitorPositionsRoute
  '/api/public/hooks/price-tick': typeof ApiPublicHooksPriceTickRoute
  '/api/public/hooks/process-orders': typeof ApiPublicHooksProcessOrdersRoute
  '/api/public/hooks/reconcile-orders': typeof ApiPublicHooksReconcileOrdersRoute
  '/api/public/hooks/run-backtests': typeof ApiPublicHooksRunBacktestsRoute
  '/api/public/hooks/sync-balances': typeof ApiPublicHooksSyncBalancesRoute
  '/api/public/hooks/sync-positions': typeof ApiPublicHooksSyncPositionsRoute
  '/api/public/hooks/webhook-signal/$token': typeof ApiPublicHooksWebhookSignalTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/control': typeof AuthenticatedAdminControlRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/parsed-signals': typeof AuthenticatedAdminParsedSignalsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/admin/risk-templates': typeof AuthenticatedAdminRiskTemplatesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/active-trades': typeof AuthenticatedAppActiveTradesRoute
  '/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/app/backtest': typeof AuthenticatedAppBacktestRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/exchanges': typeof AuthenticatedAppExchangesRoute
  '/app/heatmap': typeof AuthenticatedAppHeatmapRoute
  '/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/risk': typeof AuthenticatedAppRiskRoute
  '/app/risk-optimizer': typeof AuthenticatedAppRiskOptimizerRoute
  '/app/sources': typeof AuthenticatedAppSourcesRoute
  '/app/support': typeof AuthenticatedAppSupportRoute
  '/app/trade-history': typeof AuthenticatedAppTradeHistoryRoute
  '/sadmin/affiliates': typeof AuthenticatedSadminAffiliatesRoute
  '/sadmin/audit-logs': typeof AuthenticatedSadminAuditLogsRoute
  '/sadmin/control': typeof AuthenticatedSadminControlRoute
  '/sadmin/export': typeof AuthenticatedSadminExportRoute
  '/sadmin/monitoring': typeof AuthenticatedSadminMonitoringRoute
  '/sadmin/parsed-signals': typeof AuthenticatedSadminParsedSignalsRoute
  '/sadmin/payments': typeof AuthenticatedSadminPaymentsRoute
  '/sadmin/payouts': typeof AuthenticatedSadminPayoutsRoute
  '/sadmin/promos': typeof AuthenticatedSadminPromosRoute
  '/sadmin/rank-bonuses': typeof AuthenticatedSadminRankBonusesRoute
  '/sadmin/risk-templates': typeof AuthenticatedSadminRiskTemplatesRoute
  '/sadmin/settings': typeof AuthenticatedSadminSettingsRoute
  '/sadmin/sources': typeof AuthenticatedSadminSourcesRoute
  '/sadmin/subscriptions': typeof AuthenticatedSadminSubscriptionsRoute
  '/sadmin/support': typeof AuthenticatedSadminSupportRoute
  '/sadmin/trades': typeof AuthenticatedSadminTradesRoute
  '/sadmin/users': typeof AuthenticatedSadminUsersRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/telegram-webhook': typeof ApiPublicTelegramWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/sadmin': typeof AuthenticatedSadminIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/monitor-anomalies': typeof ApiPublicHooksMonitorAnomaliesRoute
  '/api/public/hooks/monitor-positions': typeof ApiPublicHooksMonitorPositionsRoute
  '/api/public/hooks/price-tick': typeof ApiPublicHooksPriceTickRoute
  '/api/public/hooks/process-orders': typeof ApiPublicHooksProcessOrdersRoute
  '/api/public/hooks/reconcile-orders': typeof ApiPublicHooksReconcileOrdersRoute
  '/api/public/hooks/run-backtests': typeof ApiPublicHooksRunBacktestsRoute
  '/api/public/hooks/sync-balances': typeof ApiPublicHooksSyncBalancesRoute
  '/api/public/hooks/sync-positions': typeof ApiPublicHooksSyncPositionsRoute
  '/api/public/hooks/webhook-signal/$token': typeof ApiPublicHooksWebhookSignalTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/sadmin': typeof AuthenticatedSadminRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/control': typeof AuthenticatedAdminControlRoute
  '/_authenticated/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/_authenticated/admin/parsed-signals': typeof AuthenticatedAdminParsedSignalsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/promos': typeof AuthenticatedAdminPromosRoute
  '/_authenticated/admin/risk-templates': typeof AuthenticatedAdminRiskTemplatesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/sources': typeof AuthenticatedAdminSourcesRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/app/active-trades': typeof AuthenticatedAppActiveTradesRoute
  '/_authenticated/app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/app/backtest': typeof AuthenticatedAppBacktestRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/exchanges': typeof AuthenticatedAppExchangesRoute
  '/_authenticated/app/heatmap': typeof AuthenticatedAppHeatmapRoute
  '/_authenticated/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/_authenticated/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/preferences': typeof AuthenticatedAppPreferencesRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/_authenticated/app/risk': typeof AuthenticatedAppRiskRoute
  '/_authenticated/app/risk-optimizer': typeof AuthenticatedAppRiskOptimizerRoute
  '/_authenticated/app/sources': typeof AuthenticatedAppSourcesRoute
  '/_authenticated/app/support': typeof AuthenticatedAppSupportRoute
  '/_authenticated/app/trade-history': typeof AuthenticatedAppTradeHistoryRoute
  '/_authenticated/sadmin/affiliates': typeof AuthenticatedSadminAffiliatesRoute
  '/_authenticated/sadmin/audit-logs': typeof AuthenticatedSadminAuditLogsRoute
  '/_authenticated/sadmin/control': typeof AuthenticatedSadminControlRoute
  '/_authenticated/sadmin/export': typeof AuthenticatedSadminExportRoute
  '/_authenticated/sadmin/monitoring': typeof AuthenticatedSadminMonitoringRoute
  '/_authenticated/sadmin/parsed-signals': typeof AuthenticatedSadminParsedSignalsRoute
  '/_authenticated/sadmin/payments': typeof AuthenticatedSadminPaymentsRoute
  '/_authenticated/sadmin/payouts': typeof AuthenticatedSadminPayoutsRoute
  '/_authenticated/sadmin/promos': typeof AuthenticatedSadminPromosRoute
  '/_authenticated/sadmin/rank-bonuses': typeof AuthenticatedSadminRankBonusesRoute
  '/_authenticated/sadmin/risk-templates': typeof AuthenticatedSadminRiskTemplatesRoute
  '/_authenticated/sadmin/settings': typeof AuthenticatedSadminSettingsRoute
  '/_authenticated/sadmin/sources': typeof AuthenticatedSadminSourcesRoute
  '/_authenticated/sadmin/subscriptions': typeof AuthenticatedSadminSubscriptionsRoute
  '/_authenticated/sadmin/support': typeof AuthenticatedSadminSupportRoute
  '/_authenticated/sadmin/trades': typeof AuthenticatedSadminTradesRoute
  '/_authenticated/sadmin/users': typeof AuthenticatedSadminUsersRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/payment-webhook': typeof ApiPublicPaymentWebhookRoute
  '/api/public/telegram-webhook': typeof ApiPublicTelegramWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/sadmin/': typeof AuthenticatedSadminIndexRoute
  '/api/public/hooks/dispatch-notifications': typeof ApiPublicHooksDispatchNotificationsRoute
  '/api/public/hooks/monitor-anomalies': typeof ApiPublicHooksMonitorAnomaliesRoute
  '/api/public/hooks/monitor-positions': typeof ApiPublicHooksMonitorPositionsRoute
  '/api/public/hooks/price-tick': typeof ApiPublicHooksPriceTickRoute
  '/api/public/hooks/process-orders': typeof ApiPublicHooksProcessOrdersRoute
  '/api/public/hooks/reconcile-orders': typeof ApiPublicHooksReconcileOrdersRoute
  '/api/public/hooks/run-backtests': typeof ApiPublicHooksRunBacktestsRoute
  '/api/public/hooks/sync-balances': typeof ApiPublicHooksSyncBalancesRoute
  '/api/public/hooks/sync-positions': typeof ApiPublicHooksSyncPositionsRoute
  '/api/public/hooks/webhook-signal/$token': typeof ApiPublicHooksWebhookSignalTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/auth'
    | '/faq'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/app'
    | '/sadmin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/affiliates'
    | '/admin/audit-logs'
    | '/admin/control'
    | '/admin/monitoring'
    | '/admin/parsed-signals'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/promos'
    | '/admin/risk-templates'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/trades'
    | '/admin/users'
    | '/app/active-trades'
    | '/app/analytics'
    | '/app/backtest'
    | '/app/billing'
    | '/app/exchanges'
    | '/app/heatmap'
    | '/app/leaderboard'
    | '/app/marketplace'
    | '/app/onboarding'
    | '/app/preferences'
    | '/app/profile'
    | '/app/referrals'
    | '/app/risk'
    | '/app/risk-optimizer'
    | '/app/sources'
    | '/app/support'
    | '/app/trade-history'
    | '/sadmin/affiliates'
    | '/sadmin/audit-logs'
    | '/sadmin/control'
    | '/sadmin/export'
    | '/sadmin/monitoring'
    | '/sadmin/parsed-signals'
    | '/sadmin/payments'
    | '/sadmin/payouts'
    | '/sadmin/promos'
    | '/sadmin/rank-bonuses'
    | '/sadmin/risk-templates'
    | '/sadmin/settings'
    | '/sadmin/sources'
    | '/sadmin/subscriptions'
    | '/sadmin/support'
    | '/sadmin/trades'
    | '/sadmin/users'
    | '/api/public/health'
    | '/api/public/payment-webhook'
    | '/api/public/telegram-webhook'
    | '/admin/'
    | '/app/'
    | '/sadmin/'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/monitor-anomalies'
    | '/api/public/hooks/monitor-positions'
    | '/api/public/hooks/price-tick'
    | '/api/public/hooks/process-orders'
    | '/api/public/hooks/reconcile-orders'
    | '/api/public/hooks/run-backtests'
    | '/api/public/hooks/sync-balances'
    | '/api/public/hooks/sync-positions'
    | '/api/public/hooks/webhook-signal/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/auth'
    | '/faq'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/affiliates'
    | '/admin/audit-logs'
    | '/admin/control'
    | '/admin/monitoring'
    | '/admin/parsed-signals'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/promos'
    | '/admin/risk-templates'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/trades'
    | '/admin/users'
    | '/app/active-trades'
    | '/app/analytics'
    | '/app/backtest'
    | '/app/billing'
    | '/app/exchanges'
    | '/app/heatmap'
    | '/app/leaderboard'
    | '/app/marketplace'
    | '/app/onboarding'
    | '/app/preferences'
    | '/app/profile'
    | '/app/referrals'
    | '/app/risk'
    | '/app/risk-optimizer'
    | '/app/sources'
    | '/app/support'
    | '/app/trade-history'
    | '/sadmin/affiliates'
    | '/sadmin/audit-logs'
    | '/sadmin/control'
    | '/sadmin/export'
    | '/sadmin/monitoring'
    | '/sadmin/parsed-signals'
    | '/sadmin/payments'
    | '/sadmin/payouts'
    | '/sadmin/promos'
    | '/sadmin/rank-bonuses'
    | '/sadmin/risk-templates'
    | '/sadmin/settings'
    | '/sadmin/sources'
    | '/sadmin/subscriptions'
    | '/sadmin/support'
    | '/sadmin/trades'
    | '/sadmin/users'
    | '/api/public/health'
    | '/api/public/payment-webhook'
    | '/api/public/telegram-webhook'
    | '/admin'
    | '/app'
    | '/sadmin'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/monitor-anomalies'
    | '/api/public/hooks/monitor-positions'
    | '/api/public/hooks/price-tick'
    | '/api/public/hooks/process-orders'
    | '/api/public/hooks/reconcile-orders'
    | '/api/public/hooks/run-backtests'
    | '/api/public/hooks/sync-balances'
    | '/api/public/hooks/sync-positions'
    | '/api/public/hooks/webhook-signal/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/affiliate'
    | '/auth'
    | '/faq'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/sadmin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/affiliates'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/control'
    | '/_authenticated/admin/monitoring'
    | '/_authenticated/admin/parsed-signals'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/promos'
    | '/_authenticated/admin/risk-templates'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/sources'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/trades'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/active-trades'
    | '/_authenticated/app/analytics'
    | '/_authenticated/app/backtest'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/exchanges'
    | '/_authenticated/app/heatmap'
    | '/_authenticated/app/leaderboard'
    | '/_authenticated/app/marketplace'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/preferences'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/referrals'
    | '/_authenticated/app/risk'
    | '/_authenticated/app/risk-optimizer'
    | '/_authenticated/app/sources'
    | '/_authenticated/app/support'
    | '/_authenticated/app/trade-history'
    | '/_authenticated/sadmin/affiliates'
    | '/_authenticated/sadmin/audit-logs'
    | '/_authenticated/sadmin/control'
    | '/_authenticated/sadmin/export'
    | '/_authenticated/sadmin/monitoring'
    | '/_authenticated/sadmin/parsed-signals'
    | '/_authenticated/sadmin/payments'
    | '/_authenticated/sadmin/payouts'
    | '/_authenticated/sadmin/promos'
    | '/_authenticated/sadmin/rank-bonuses'
    | '/_authenticated/sadmin/risk-templates'
    | '/_authenticated/sadmin/settings'
    | '/_authenticated/sadmin/sources'
    | '/_authenticated/sadmin/subscriptions'
    | '/_authenticated/sadmin/support'
    | '/_authenticated/sadmin/trades'
    | '/_authenticated/sadmin/users'
    | '/api/public/health'
    | '/api/public/payment-webhook'
    | '/api/public/telegram-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/sadmin/'
    | '/api/public/hooks/dispatch-notifications'
    | '/api/public/hooks/monitor-anomalies'
    | '/api/public/hooks/monitor-positions'
    | '/api/public/hooks/price-tick'
    | '/api/public/hooks/process-orders'
    | '/api/public/hooks/reconcile-orders'
    | '/api/public/hooks/run-backtests'
    | '/api/public/hooks/sync-balances'
    | '/api/public/hooks/sync-positions'
    | '/api/public/hooks/webhook-signal/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AffiliateRoute: typeof AffiliateRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicPaymentWebhookRoute: typeof ApiPublicPaymentWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicHooksDispatchNotificationsRoute: typeof ApiPublicHooksDispatchNotificationsRoute
  ApiPublicHooksMonitorAnomaliesRoute: typeof ApiPublicHooksMonitorAnomaliesRoute
  ApiPublicHooksMonitorPositionsRoute: typeof ApiPublicHooksMonitorPositionsRoute
  ApiPublicHooksPriceTickRoute: typeof ApiPublicHooksPriceTickRoute
  ApiPublicHooksProcessOrdersRoute: typeof ApiPublicHooksProcessOrdersRoute
  ApiPublicHooksReconcileOrdersRoute: typeof ApiPublicHooksReconcileOrdersRoute
  ApiPublicHooksRunBacktestsRoute: typeof ApiPublicHooksRunBacktestsRoute
  ApiPublicHooksSyncBalancesRoute: typeof ApiPublicHooksSyncBalancesRoute
  ApiPublicHooksSyncPositionsRoute: typeof ApiPublicHooksSyncPositionsRoute
  ApiPublicHooksWebhookSignalTokenRoute: typeof ApiPublicHooksWebhookSignalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sadmin': {
      id: '/_authenticated/sadmin'
      path: '/sadmin'
      fullPath: '/sadmin'
      preLoaderRoute: typeof AuthenticatedSadminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/affiliates': {
      id: '/_authenticated/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AuthenticatedAdminAffiliatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/control': {
      id: '/_authenticated/admin/control'
      path: '/control'
      fullPath: '/admin/control'
      preLoaderRoute: typeof AuthenticatedAdminControlRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/monitoring': {
      id: '/_authenticated/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AuthenticatedAdminMonitoringRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parsed-signals': {
      id: '/_authenticated/admin/parsed-signals'
      path: '/parsed-signals'
      fullPath: '/admin/parsed-signals'
      preLoaderRoute: typeof AuthenticatedAdminParsedSignalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promos': {
      id: '/_authenticated/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AuthenticatedAdminPromosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/risk-templates': {
      id: '/_authenticated/admin/risk-templates'
      path: '/risk-templates'
      fullPath: '/admin/risk-templates'
      preLoaderRoute: typeof AuthenticatedAdminRiskTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sources': {
      id: '/_authenticated/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AuthenticatedAdminSourcesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trades': {
      id: '/_authenticated/admin/trades'
      path: '/trades'
      fullPath: '/admin/trades'
      preLoaderRoute: typeof AuthenticatedAdminTradesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/active-trades': {
      id: '/_authenticated/app/active-trades'
      path: '/active-trades'
      fullPath: '/app/active-trades'
      preLoaderRoute: typeof AuthenticatedAppActiveTradesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/analytics': {
      id: '/_authenticated/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/backtest': {
      id: '/_authenticated/app/backtest'
      path: '/backtest'
      fullPath: '/app/backtest'
      preLoaderRoute: typeof AuthenticatedAppBacktestRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/exchanges': {
      id: '/_authenticated/app/exchanges'
      path: '/exchanges'
      fullPath: '/app/exchanges'
      preLoaderRoute: typeof AuthenticatedAppExchangesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/heatmap': {
      id: '/_authenticated/app/heatmap'
      path: '/heatmap'
      fullPath: '/app/heatmap'
      preLoaderRoute: typeof AuthenticatedAppHeatmapRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leaderboard': {
      id: '/_authenticated/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AuthenticatedAppLeaderboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/marketplace': {
      id: '/_authenticated/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/preferences': {
      id: '/_authenticated/app/preferences'
      path: '/preferences'
      fullPath: '/app/preferences'
      preLoaderRoute: typeof AuthenticatedAppPreferencesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/referrals': {
      id: '/_authenticated/app/referrals'
      path: '/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AuthenticatedAppReferralsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/risk': {
      id: '/_authenticated/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AuthenticatedAppRiskRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/risk-optimizer': {
      id: '/_authenticated/app/risk-optimizer'
      path: '/risk-optimizer'
      fullPath: '/app/risk-optimizer'
      preLoaderRoute: typeof AuthenticatedAppRiskOptimizerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sources': {
      id: '/_authenticated/app/sources'
      path: '/sources'
      fullPath: '/app/sources'
      preLoaderRoute: typeof AuthenticatedAppSourcesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/support': {
      id: '/_authenticated/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AuthenticatedAppSupportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/trade-history': {
      id: '/_authenticated/app/trade-history'
      path: '/trade-history'
      fullPath: '/app/trade-history'
      preLoaderRoute: typeof AuthenticatedAppTradeHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/sadmin/': {
      id: '/_authenticated/sadmin/'
      path: '/'
      fullPath: '/sadmin/'
      preLoaderRoute: typeof AuthenticatedSadminIndexRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/affiliates': {
      id: '/_authenticated/sadmin/affiliates'
      path: '/affiliates'
      fullPath: '/sadmin/affiliates'
      preLoaderRoute: typeof AuthenticatedSadminAffiliatesRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/audit-logs': {
      id: '/_authenticated/sadmin/audit-logs'
      path: '/audit-logs'
      fullPath: '/sadmin/audit-logs'
      preLoaderRoute: typeof AuthenticatedSadminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/control': {
      id: '/_authenticated/sadmin/control'
      path: '/control'
      fullPath: '/sadmin/control'
      preLoaderRoute: typeof AuthenticatedSadminControlRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/export': {
      id: '/_authenticated/sadmin/export'
      path: '/export'
      fullPath: '/sadmin/export'
      preLoaderRoute: typeof AuthenticatedSadminExportRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/monitoring': {
      id: '/_authenticated/sadmin/monitoring'
      path: '/monitoring'
      fullPath: '/sadmin/monitoring'
      preLoaderRoute: typeof AuthenticatedSadminMonitoringRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/parsed-signals': {
      id: '/_authenticated/sadmin/parsed-signals'
      path: '/parsed-signals'
      fullPath: '/sadmin/parsed-signals'
      preLoaderRoute: typeof AuthenticatedSadminParsedSignalsRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/payments': {
      id: '/_authenticated/sadmin/payments'
      path: '/payments'
      fullPath: '/sadmin/payments'
      preLoaderRoute: typeof AuthenticatedSadminPaymentsRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/payouts': {
      id: '/_authenticated/sadmin/payouts'
      path: '/payouts'
      fullPath: '/sadmin/payouts'
      preLoaderRoute: typeof AuthenticatedSadminPayoutsRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/promos': {
      id: '/_authenticated/sadmin/promos'
      path: '/promos'
      fullPath: '/sadmin/promos'
      preLoaderRoute: typeof AuthenticatedSadminPromosRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/rank-bonuses': {
      id: '/_authenticated/sadmin/rank-bonuses'
      path: '/rank-bonuses'
      fullPath: '/sadmin/rank-bonuses'
      preLoaderRoute: typeof AuthenticatedSadminRankBonusesRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/risk-templates': {
      id: '/_authenticated/sadmin/risk-templates'
      path: '/risk-templates'
      fullPath: '/sadmin/risk-templates'
      preLoaderRoute: typeof AuthenticatedSadminRiskTemplatesRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/settings': {
      id: '/_authenticated/sadmin/settings'
      path: '/settings'
      fullPath: '/sadmin/settings'
      preLoaderRoute: typeof AuthenticatedSadminSettingsRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/sources': {
      id: '/_authenticated/sadmin/sources'
      path: '/sources'
      fullPath: '/sadmin/sources'
      preLoaderRoute: typeof AuthenticatedSadminSourcesRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/subscriptions': {
      id: '/_authenticated/sadmin/subscriptions'
      path: '/subscriptions'
      fullPath: '/sadmin/subscriptions'
      preLoaderRoute: typeof AuthenticatedSadminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/support': {
      id: '/_authenticated/sadmin/support'
      path: '/support'
      fullPath: '/sadmin/support'
      preLoaderRoute: typeof AuthenticatedSadminSupportRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/trades': {
      id: '/_authenticated/sadmin/trades'
      path: '/trades'
      fullPath: '/sadmin/trades'
      preLoaderRoute: typeof AuthenticatedSadminTradesRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/_authenticated/sadmin/users': {
      id: '/_authenticated/sadmin/users'
      path: '/users'
      fullPath: '/sadmin/users'
      preLoaderRoute: typeof AuthenticatedSadminUsersRouteImport
      parentRoute: typeof AuthenticatedSadminRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payment-webhook': {
      id: '/api/public/payment-webhook'
      path: '/api/public/payment-webhook'
      fullPath: '/api/public/payment-webhook'
      preLoaderRoute: typeof ApiPublicPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-webhook': {
      id: '/api/public/telegram-webhook'
      path: '/api/public/telegram-webhook'
      fullPath: '/api/public/telegram-webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-notifications': {
      id: '/api/public/hooks/dispatch-notifications'
      path: '/api/public/hooks/dispatch-notifications'
      fullPath: '/api/public/hooks/dispatch-notifications'
      preLoaderRoute: typeof ApiPublicHooksDispatchNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-anomalies': {
      id: '/api/public/hooks/monitor-anomalies'
      path: '/api/public/hooks/monitor-anomalies'
      fullPath: '/api/public/hooks/monitor-anomalies'
      preLoaderRoute: typeof ApiPublicHooksMonitorAnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-positions': {
      id: '/api/public/hooks/monitor-positions'
      path: '/api/public/hooks/monitor-positions'
      fullPath: '/api/public/hooks/monitor-positions'
      preLoaderRoute: typeof ApiPublicHooksMonitorPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/price-tick': {
      id: '/api/public/hooks/price-tick'
      path: '/api/public/hooks/price-tick'
      fullPath: '/api/public/hooks/price-tick'
      preLoaderRoute: typeof ApiPublicHooksPriceTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-orders': {
      id: '/api/public/hooks/process-orders'
      path: '/api/public/hooks/process-orders'
      fullPath: '/api/public/hooks/process-orders'
      preLoaderRoute: typeof ApiPublicHooksProcessOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconcile-orders': {
      id: '/api/public/hooks/reconcile-orders'
      path: '/api/public/hooks/reconcile-orders'
      fullPath: '/api/public/hooks/reconcile-orders'
      preLoaderRoute: typeof ApiPublicHooksReconcileOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-backtests': {
      id: '/api/public/hooks/run-backtests'
      path: '/api/public/hooks/run-backtests'
      fullPath: '/api/public/hooks/run-backtests'
      preLoaderRoute: typeof ApiPublicHooksRunBacktestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-balances': {
      id: '/api/public/hooks/sync-balances'
      path: '/api/public/hooks/sync-balances'
      fullPath: '/api/public/hooks/sync-balances'
      preLoaderRoute: typeof ApiPublicHooksSyncBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-positions': {
      id: '/api/public/hooks/sync-positions'
      path: '/api/public/hooks/sync-positions'
      fullPath: '/api/public/hooks/sync-positions'
      preLoaderRoute: typeof ApiPublicHooksSyncPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/webhook-signal/$token': {
      id: '/api/public/hooks/webhook-signal/$token'
      path: '/api/public/hooks/webhook-signal/$token'
      fullPath: '/api/public/hooks/webhook-signal/$token'
      preLoaderRoute: typeof ApiPublicHooksWebhookSignalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAffiliatesRoute: typeof AuthenticatedAdminAffiliatesRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminControlRoute: typeof AuthenticatedAdminControlRoute
  AuthenticatedAdminMonitoringRoute: typeof AuthenticatedAdminMonitoringRoute
  AuthenticatedAdminParsedSignalsRoute: typeof AuthenticatedAdminParsedSignalsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminPromosRoute: typeof AuthenticatedAdminPromosRoute
  AuthenticatedAdminRiskTemplatesRoute: typeof AuthenticatedAdminRiskTemplatesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSourcesRoute: typeof AuthenticatedAdminSourcesRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTradesRoute: typeof AuthenticatedAdminTradesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAffiliatesRoute: AuthenticatedAdminAffiliatesRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminControlRoute: AuthenticatedAdminControlRoute,
  AuthenticatedAdminMonitoringRoute: AuthenticatedAdminMonitoringRoute,
  AuthenticatedAdminParsedSignalsRoute: AuthenticatedAdminParsedSignalsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
  AuthenticatedAdminPromosRoute: AuthenticatedAdminPromosRoute,
  AuthenticatedAdminRiskTemplatesRoute: AuthenticatedAdminRiskTemplatesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSourcesRoute: AuthenticatedAdminSourcesRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminTradesRoute: AuthenticatedAdminTradesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppActiveTradesRoute: typeof AuthenticatedAppActiveTradesRoute
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppBacktestRoute: typeof AuthenticatedAppBacktestRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppExchangesRoute: typeof AuthenticatedAppExchangesRoute
  AuthenticatedAppHeatmapRoute: typeof AuthenticatedAppHeatmapRoute
  AuthenticatedAppLeaderboardRoute: typeof AuthenticatedAppLeaderboardRoute
  AuthenticatedAppMarketplaceRoute: typeof AuthenticatedAppMarketplaceRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppPreferencesRoute: typeof AuthenticatedAppPreferencesRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppReferralsRoute: typeof AuthenticatedAppReferralsRoute
  AuthenticatedAppRiskRoute: typeof AuthenticatedAppRiskRoute
  AuthenticatedAppRiskOptimizerRoute: typeof AuthenticatedAppRiskOptimizerRoute
  AuthenticatedAppSourcesRoute: typeof AuthenticatedAppSourcesRoute
  AuthenticatedAppSupportRoute: typeof AuthenticatedAppSupportRoute
  AuthenticatedAppTradeHistoryRoute: typeof AuthenticatedAppTradeHistoryRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppActiveTradesRoute: AuthenticatedAppActiveTradesRoute,
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppBacktestRoute: AuthenticatedAppBacktestRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppExchangesRoute: AuthenticatedAppExchangesRoute,
  AuthenticatedAppHeatmapRoute: AuthenticatedAppHeatmapRoute,
  AuthenticatedAppLeaderboardRoute: AuthenticatedAppLeaderboardRoute,
  AuthenticatedAppMarketplaceRoute: AuthenticatedAppMarketplaceRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppPreferencesRoute: AuthenticatedAppPreferencesRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppReferralsRoute: AuthenticatedAppReferralsRoute,
  AuthenticatedAppRiskRoute: AuthenticatedAppRiskRoute,
  AuthenticatedAppRiskOptimizerRoute: AuthenticatedAppRiskOptimizerRoute,
  AuthenticatedAppSourcesRoute: AuthenticatedAppSourcesRoute,
  AuthenticatedAppSupportRoute: AuthenticatedAppSupportRoute,
  AuthenticatedAppTradeHistoryRoute: AuthenticatedAppTradeHistoryRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedSadminRouteChildren {
  AuthenticatedSadminAffiliatesRoute: typeof AuthenticatedSadminAffiliatesRoute
  AuthenticatedSadminAuditLogsRoute: typeof AuthenticatedSadminAuditLogsRoute
  AuthenticatedSadminControlRoute: typeof AuthenticatedSadminControlRoute
  AuthenticatedSadminExportRoute: typeof AuthenticatedSadminExportRoute
  AuthenticatedSadminMonitoringRoute: typeof AuthenticatedSadminMonitoringRoute
  AuthenticatedSadminParsedSignalsRoute: typeof AuthenticatedSadminParsedSignalsRoute
  AuthenticatedSadminPaymentsRoute: typeof AuthenticatedSadminPaymentsRoute
  AuthenticatedSadminPayoutsRoute: typeof AuthenticatedSadminPayoutsRoute
  AuthenticatedSadminPromosRoute: typeof AuthenticatedSadminPromosRoute
  AuthenticatedSadminRankBonusesRoute: typeof AuthenticatedSadminRankBonusesRoute
  AuthenticatedSadminRiskTemplatesRoute: typeof AuthenticatedSadminRiskTemplatesRoute
  AuthenticatedSadminSettingsRoute: typeof AuthenticatedSadminSettingsRoute
  AuthenticatedSadminSourcesRoute: typeof AuthenticatedSadminSourcesRoute
  AuthenticatedSadminSubscriptionsRoute: typeof AuthenticatedSadminSubscriptionsRoute
  AuthenticatedSadminSupportRoute: typeof AuthenticatedSadminSupportRoute
  AuthenticatedSadminTradesRoute: typeof AuthenticatedSadminTradesRoute
  AuthenticatedSadminUsersRoute: typeof AuthenticatedSadminUsersRoute
  AuthenticatedSadminIndexRoute: typeof AuthenticatedSadminIndexRoute
}

const AuthenticatedSadminRouteChildren: AuthenticatedSadminRouteChildren = {
  AuthenticatedSadminAffiliatesRoute: AuthenticatedSadminAffiliatesRoute,
  AuthenticatedSadminAuditLogsRoute: AuthenticatedSadminAuditLogsRoute,
  AuthenticatedSadminControlRoute: AuthenticatedSadminControlRoute,
  AuthenticatedSadminExportRoute: AuthenticatedSadminExportRoute,
  AuthenticatedSadminMonitoringRoute: AuthenticatedSadminMonitoringRoute,
  AuthenticatedSadminParsedSignalsRoute: AuthenticatedSadminParsedSignalsRoute,
  AuthenticatedSadminPaymentsRoute: AuthenticatedSadminPaymentsRoute,
  AuthenticatedSadminPayoutsRoute: AuthenticatedSadminPayoutsRoute,
  AuthenticatedSadminPromosRoute: AuthenticatedSadminPromosRoute,
  AuthenticatedSadminRankBonusesRoute: AuthenticatedSadminRankBonusesRoute,
  AuthenticatedSadminRiskTemplatesRoute: AuthenticatedSadminRiskTemplatesRoute,
  AuthenticatedSadminSettingsRoute: AuthenticatedSadminSettingsRoute,
  AuthenticatedSadminSourcesRoute: AuthenticatedSadminSourcesRoute,
  AuthenticatedSadminSubscriptionsRoute: AuthenticatedSadminSubscriptionsRoute,
  AuthenticatedSadminSupportRoute: AuthenticatedSadminSupportRoute,
  AuthenticatedSadminTradesRoute: AuthenticatedSadminTradesRoute,
  AuthenticatedSadminUsersRoute: AuthenticatedSadminUsersRoute,
  AuthenticatedSadminIndexRoute: AuthenticatedSadminIndexRoute,
}

const AuthenticatedSadminRouteWithChildren =
  AuthenticatedSadminRoute._addFileChildren(AuthenticatedSadminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedSadminRoute: typeof AuthenticatedSadminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedSadminRoute: AuthenticatedSadminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AffiliateRoute: AffiliateRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicPaymentWebhookRoute: ApiPublicPaymentWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicHooksDispatchNotificationsRoute:
    ApiPublicHooksDispatchNotificationsRoute,
  ApiPublicHooksMonitorAnomaliesRoute: ApiPublicHooksMonitorAnomaliesRoute,
  ApiPublicHooksMonitorPositionsRoute: ApiPublicHooksMonitorPositionsRoute,
  ApiPublicHooksPriceTickRoute: ApiPublicHooksPriceTickRoute,
  ApiPublicHooksProcessOrdersRoute: ApiPublicHooksProcessOrdersRoute,
  ApiPublicHooksReconcileOrdersRoute: ApiPublicHooksReconcileOrdersRoute,
  ApiPublicHooksRunBacktestsRoute: ApiPublicHooksRunBacktestsRoute,
  ApiPublicHooksSyncBalancesRoute: ApiPublicHooksSyncBalancesRoute,
  ApiPublicHooksSyncPositionsRoute: ApiPublicHooksSyncPositionsRoute,
  ApiPublicHooksWebhookSignalTokenRoute: ApiPublicHooksWebhookSignalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
